name: Run all unit tests
on: [ push, pull_request ]

jobs:
  CompileAndUnitTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Compile
        run: mvn compile
      - name: Run tests
        run: mvn test
      - name: Build Jar
        run: mvn package
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-actions-test.jar
          path: target/github-actions-test.jar
      - name: Store Dockerfile
        uses: actions/upload-artifact@v2
        with:
          name: Dockerfile
          path: Dockerfile

  BuildDockerImage:
    runs-on: ubuntu-latest
    needs: CompileAndUnitTest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: github-actions-test.jar
          path: target
      - name: Download Dockerfile
        uses: actions/download-artifact@v2
        with:
          name: Dockerfile
          path: .
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: github-actions-test:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}