name: Run all unit tests
on: [ push, pull_request ]

jobs:
  CompileAndUnitTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven Compile
        run: mvn compile
      - name: Run tests
        run: mvn test